version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "bc" # This will name the executable inside the zip file "bc" (or "bc.exe")

archives:
  - name_template: "bc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip # Windows users prefer .zip over .tar.gz

checksum:
  name_template: "bc_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  disable: true
